# Generated by Django 3.1.2 on 2020-12-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(max_length=9)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ClubFutbolApp')),
            ],
            options={
                'verbose_name': 'club',
                'verbose_name_plural': 'clubs',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_nombre', models.CharField(max_length=30)),
                ('entrenador', models.CharField(max_length=30)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubFutbolApp.categoria')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubFutbolApp.club')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'posicion',
                'verbose_name_plural': 'posiciones',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jug_nombre', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Jugadores')),
                ('fecha_nacimiento', models.DateTimeField()),
                ('dorsal', models.IntegerField(max_length=2)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubFutbolApp.equipo')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubFutbolApp.posicion')),
            ],
            options={
                'verbose_name': 'jugador',
                'verbose_name_plural': 'jugadores',
            },
        ),
    ]
