# Generated by Django 3.1.2 on 2020-12-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFutbolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
