# Generated by Django 3.1.2 on 2020-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFutbolApp', '0005_auto_20201204_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospartido',
            name='titular',
            field=models.BooleanField(blank=True, choices=[('True', 'Titular'), ('False', 'Suplente')], null=True),
        ),
    ]
