# Generated by Django 3.1.2 on 2020-12-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFutbolApp', '0007_auto_20201204_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospartido',
            name='goles',
            field=models.IntegerField(blank=True),
        ),
    ]
