# Generated by Django 3.1.2 on 2020-12-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFutbolApp', '0008_auto_20201204_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='resultado_equipo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partido',
            name='resultado_rival',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datospartido',
            name='goles',
            field=models.IntegerField(default=0),
        ),
    ]
