# Generated by Django 3.1.2 on 2020-12-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFutbolApp', '0009_auto_20201218_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datospartido',
            options={'ordering': ['jugador_convocado'], 'verbose_name': 'datospartido', 'verbose_name_plural': 'datospartidos'},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['equipo', 'jug_nombre'], 'verbose_name': 'jugador', 'verbose_name_plural': 'jugadores'},
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['equipo', 'rival'], 'verbose_name': 'partido', 'verbose_name_plural': 'partidos'},
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultado_equipo',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultado_rival',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
