# Generated by Django 3.1.2 on 2020-12-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFutbolApp', '0011_auto_20201229_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='n_jornada',
            field=models.IntegerField(max_length=2),
        ),
    ]
